export const GET_DEPARTMENTS_REQUEST = 'GET_DEPARTMENTS_REQUEST';
export const GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS';
export const GET_DEPARTMENTS_ERROR = 'GET_DEPARTMENTS_ERROR';
export const DISMISS_DEPARTMENTS_ERROR = 'DISMISS_DEPARTMENTS_ERROR';